### ISSUE TITLE
mariadb persistance is not documented correcly

### ISSUE THREAD

**Issue by couillonnade** [k8s-land/gitea-chart#26]
Hello,

there is a mistake in the documentation for MariaDB persistence. It states that you should set mariadb.persistence.enabled to true but it as actually mariadb.master.persistence.enabled (see sample below). Without it, it only create volumes with EmptyDir that does not survive if the pod is deleted or moved to another node.

Also if you want to support upgrades, you have to set **both** the db user password (mariadb.db.password) **and** root user (mariadb.rootUser.password). Again, without these, if you delete the deployment or pods, it won't restart properly.

I may have a look at the chart and propose an alternative in the sed command in init for the user password as well as check the rootpassword (force to use the secret if exists, there is a parameter in bitnami chart for that) if you are interested.

In the meantime, here is a working example of values:

```
mariadb:
    master:
      persistence:
        enabled: true
        storageClass: "yourstorageclass"
        accessMode: ReadWriteOnce
        size: 8Gi
    rootUser:
      password: "yourpass"
    db:
      enabled: true
      name: "gitea"
      user: "gitea"
      password: "yourpass"
```
